### ISSUE TITLE
libressl support for dev-libs/libstrophe

### ISSUE THREAD

**Issue by benaryorg** [megabaks/stuff#90]
Well, I'm using `net-im/profanity` and it depends on `dev-libs/libstrophe` which is strictly dependent on openssl and doesn't have the usual libressl use-flag for switching to libressl.

This is currently the only thing preventing me from using libressl on my system.

I however do not have any idea whether it would just work to add the dependency switch or if something in the libstrophe source needs change for this to work.
At least the [Gentoo Wiki page for LibreSSL](https://wiki.gentoo.org/wiki/Project:LibreSSL) says changing the dependencies should work.

**Comment by pasis** [comment]
I'd like to add libressl option, but I didn't do that because I haven't find proper way to do so. There is a gentoo-like distro which introduces such a thing as `provider` which perfectly describes what you want to achieve. I didn't investigated too much in openssl question, but I found out a virtual/openssl package proposal which is not in main tree. It would solve the problem. As far as I understand openssl and libressl blocks each other? if yes, I can make dependency in this way:
```
RDEPEND="
    || (
        dev-libs/openssl
        dev-libs/libressl
    )"
```
Or (as suggested) introduce libressl use-flag. I'll appreciate any help with choosing proper way.

**Comment by benaryorg** [comment]
Quoting my earlier link which does specify exactly what to do:

> Much of the preliminary work has been done on GitHub. There an overlay has been set up to test ebuilds for difficult packages before they land in the tree. For most packages, migration is as simple as just replacing the openssl atom with a choice between openssl and libressl. Here are some exmaples:
> ```
> ssl? ( dev-libs/openssl:0 )
> ```
>
> with
> ```
> ssl? (
>   !libressl? ( dev-libs/openssl:0= )
>   libressl? ( dev-libs/libressl:0= )
> )
> ```
> Notice that we add the sub-slot operator for both libressl and openssl. 

So I assume just copying that should work.

**Comment by pasis** [comment]
Done: bfe133f9a50d6f92749d42560eba5be5aad16bd0. Please, check it.

**Comment by benaryorg** [comment]
Seems to work, at least profanity works after recompiling half my system.

Thank you very much!
